import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Capacitor, registerPlugin } from '@capacitor/core';
import { App as NativeApp } from '@capacitor/app';
import { Preferences } from '@capacitor/preferences';
import { LocalNotifications } from '@capacitor/local-notifications';
import { ArrowLeft, ArrowRight, Plus, Shield, Leaf, Clock3, Settings, Trash2, Download } from 'lucide-react';
import './spending.css';
const Guard = registerPlugin('SpendingGuard');
const KEY = 'second-thought-spending-v1';
const defaults = ['Did I plan to buy this before today?', 'Do I already own something that serves the same purpose?', 'Can this wait?', 'What would keeping this money protect or pay for?', 'Am I shopping because I need the item or because of how I feel?'];
const WAIT_OPTIONS = [[3, '3 hours'], [12, '12 hours'], [24, '24 hours'], [48, '48 hours']];
const fresh = () => ({ items: [], goals: [], apps: [], urges: 0, best: 0, settings: { protection: false, notifications: false, cooldown: 24, access: 10, questions: defaults, protectionConsent: false } });
const dollars = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(+n || 0);
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const date = n => new Date(n).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
const left = n => { const minutes = Math.ceil((n - Date.now()) / 60000); return minutes <= 0 ? 'Ready to decide' : minutes < 60 ? `${minutes}m left` : minutes < 48 * 60 ? `${Math.ceil(minutes / 60)}h left` : `${Math.ceil(minutes / 1440)} days left`; };
const streak = items => { const bought = items.filter(i => i.status === 'purchased' && i.kind === 'impulse').map(i => i.resolvedAt); const since = bought.length ? Math.max(...bought) : Math.min(Date.now(), ...items.map(i => i.createdAt)); return Math.floor((Date.now() - since) / 86400000); };
const emptyDraft = () => ({ name: '', price: '', category: 'Other', link: '', why: '', trigger: '', kind: 'impulse' });
function App() {
 const [state, setState] = useState(fresh), [ready, setReady] = useState(false), [page, setPage] = useState('home'), [draft, setDraft] = useState(emptyDraft), [answers, setAnswers] = useState({}), [selected, setSelected] = useState(null), [custom, setCustom] = useState(''), [goalDraft, setGoalDraft] = useState({ name: '', icon: '🌱', target: '', deadline: '' }), [installed, setInstalled] = useState([]), [accessibility, setAccessibility] = useState(false), [message, setMessage] = useState(''), [showDisclosure, setShowDisclosure] = useState(false), [disclosureAccepted, setDisclosureAccepted] = useState(false), [now, setNow] = useState(Date.now());
 const native = Capacitor.getPlatform() === 'android';
 const set = fn => setState(d => typeof fn === 'function' ? fn(d) : { ...d, ...fn });
 const setting = (name, value) => set(d => ({ ...d, settings: { ...d.settings, [name]: value } }));
 const go = p => { setMessage(''); setShowDisclosure(false); setPage(p); window.scrollTo(0, 0); };
 useEffect(() => { Preferences.get({ key: KEY }).then(({ value }) => { if (value) try { const saved = JSON.parse(value); setState({ ...fresh(), ...saved, settings: { ...fresh().settings, ...saved.settings, protection: Boolean(saved.settings?.protection && saved.settings?.protectionConsent), protectionConsent: Boolean(saved.settings?.protectionConsent), cooldown: WAIT_OPTIONS.some(([h]) => h === saved.settings?.cooldown) ? saved.settings.cooldown : 24 } }); } catch {} setReady(true); }); const timer = setInterval(() => setNow(Date.now()), 60000); return () => clearInterval(timer); }, []);
 useEffect(() => { if (ready) Preferences.set({ key: KEY, value: JSON.stringify(state) }); }, [state, ready]);
 useEffect(() => { if (message === 'Add an item name and a valid price.' && draft.name.trim() && draft.price !== '' && Number.isFinite(Number(draft.price)) && Number(draft.price) >= 0) setMessage(''); if (message === 'Enter a waiting time in minutes.' && Number.isInteger(Number(custom)) && Number(custom) > 0) setMessage(''); if (message === 'Add a name and target above zero.' && goalDraft.name.trim() && Number(goalDraft.target) > 0) setMessage(''); if (message === 'Choose at least one app first.' && state.apps.length) setMessage(''); }, [draft, goalDraft, custom, state.apps, message]);
 const startProtection = () => { if (!native) return setMessage('Install the Android app to protect shopping apps.'); if (!state.apps.length) return setMessage('Choose at least one app first.'); setDisclosureAccepted(false); setShowDisclosure(true); };
 const confirmProtection = async () => { if (!disclosureAccepted) return; try { await Guard.configure({ packages: state.apps, protection: true, consent: true, durationMinutes: Number(state.settings.access), goal: state.goals[0]?.name || 'Your goal', protectedAmount: dollars(state.items.filter(i => i.status === 'skipped').reduce((sum,i) => sum + Number(i.price),0)) }); set(d => ({ ...d, settings: { ...d.settings, protection: true, protectionConsent: true } })); setShowDisclosure(false); await Guard.openAccessibilitySettings(); } catch { setMessage('Could not open Android accessibility settings.'); } };
 const protectedAmount = state.items.filter(i => i.status === 'skipped').reduce((sum, i) => sum + Number(i.price), 0);
 const waiting = state.items.filter(i => i.status === 'waiting');
 const currentStreak = streak(state.items);
 useEffect(() => { if (!native || !ready) return; const refresh = async () => { try { const s = await Guard.status(); setAccessibility(s.enabled); setInstalled((await Guard.listApps()).apps || []); } catch {} }; const handleUrl = url => { if (url?.includes('add-item')) go('new'); if (url?.includes('protection-off')) { set(d => ({ ...d, settings: { ...d.settings, protection: false, protectionConsent: false } })); go('apps'); } }; refresh(); const resume = NativeApp.addListener('resume', refresh); const url = NativeApp.addListener('appUrlOpen', ({ url }) => handleUrl(url)); NativeApp.getLaunchUrl().then(result => handleUrl(result?.url)); return () => { resume.then(x => x.remove()); url.then(x => x.remove()); }; }, [native, ready]);
 useEffect(() => { if (native && ready) Guard.configure({ packages: state.apps, protection: state.settings.protection, consent: state.settings.protectionConsent, durationMinutes: Number(state.settings.access), goal: state.goals[0]?.name || 'Your goal', protectedAmount: dollars(protectedAmount) }).catch(() => {}); }, [state, ready, native]);
 const schedule = async item => { if (!native || !state.settings.notifications) return; try { if ((await LocalNotifications.checkPermissions()).display === 'granted') await LocalNotifications.schedule({ notifications: [{ id: Math.floor(Math.random() * 2000000000), title: 'Your pause is complete', body: `${item.name} is ready for another look.`, schedule: { at: new Date(item.until) } }] }); } catch {} };
 const add = hours => { const price = Number(draft.price); if (!draft.name.trim() || !Number.isFinite(price) || price < 0 || !draft.price) return setMessage('Add an item name and a valid price.'); if (!(hours > 0) || !Number.isFinite(hours)) return setMessage('Enter a waiting time in minutes.'); const item = { ...draft, id: uid(), name: draft.name.trim(), price, createdAt: Date.now(), until: Date.now() + hours * 3600000, status: 'waiting', answers, extensions: 0 }; set(d => ({ ...d, urges: d.urges + 1, items: [item, ...d.items] })); setDraft(emptyDraft()); setAnswers({}); go('wishlist'); schedule(item); };
 const decide = (status, goalId = '') => { const item = selected; set(d => ({ ...d, best: Math.max(d.best, streak(d.items)), items: d.items.map(i => i.id === item.id ? { ...i, status, resolvedAt: Date.now(), goalId } : i), goals: status === 'skipped' && goalId ? d.goals.map(g => g.id === goalId ? { ...g, protected: (g.protected || 0) + item.price } : g) : d.goals })); setSelected(null); };
 const extend = hours => { const item = selected, until = Date.now() + hours * 3600000; set(d => ({ ...d, items: d.items.map(i => i.id === item.id ? { ...i, until, extensions: i.extensions + 1 } : i) })); setSelected(null); schedule({ ...item, until }); };
 const exportData = () => { if (native) { Guard.exportData({ content: JSON.stringify(state, null, 2) }).then(result => { if (!result.saved) setMessage('Export canceled.'); }).catch(() => setMessage('Export could not be saved.')); return; } const url = URL.createObjectURL(new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'second-thought-spending.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
 const reset = async () => { if (!confirm('Delete all items, goals, and settings from this device? This cannot be undone.')) return; if (native) await Guard.configure({ packages: [], protection: false, consent: false, durationMinutes: 10, goal: '', protectedAmount: '$0.00' }).catch(() => {}); try { if (native) { const pending = await LocalNotifications.getPending(); if (pending.notifications.length) await LocalNotifications.cancel({ notifications: pending.notifications.map(n => ({ id: n.id })) }); } } catch {} await Preferences.remove({ key: KEY }); setState(fresh()); go('home'); };
 const skipped = state.items.filter(i => i.status === 'skipped').length;
 const back = to => <button className="back" onClick={() => go(to || 'home')}><ArrowLeft size={16}/> Back</button>;
 const goalCard = g => <div className="card" key={g.id}><div className="row"><b>{g.icon} {g.name}</b><span>{dollars(g.protected)} / {dollars(g.target)}</span></div><div className="progress"><i style={{ width: `${Math.min(100, (g.protected || 0) / g.target * 100)}%` }}/></div><small>Estimated money protected{g.deadline ? ` · deadline ${g.deadline}` : ''}</small></div>;
 if (!ready) return null;
 return <div className="shell"><header><div className="brand"><span className="brand-icon">✳</span><span>SECOND THOUGHT <small>SPENDING</small></span></div><button className="icon-button" aria-label="Settings" onClick={() => go('settings')}><Settings size={20}/></button></header><main>
 {page === 'home' && <><div className="eyebrow">ONE PAUSE BETWEEN IMPULSE AND PURCHASE</div><h1>Make room for a<br/><em>second thought.</em></h1><p className="lead">A little space to choose what matters to you. Every pause counts.</p><button className="primary big" onClick={() => go('new')}><Plus size={20}/> I want to buy something <ArrowRight size={18}/></button><div className="hero-card"><div className="plant">{protectedAmount >= 500 ? '🌳' : protectedAmount >= 100 ? '🪴' : '🌱'}</div><div><div className="eyebrow">YOUR GROWING SPACE</div><strong>{dollars(protectedAmount)}</strong><p>Money protected by purchases you skipped. No money has been moved.</p></div></div><div className="stat-grid"><div className="stat"><b>{currentStreak} days</b><span>No impulse buy streak</span></div><div className="stat"><b>{waiting.length}</b><span>Cooling down</span></div><div className="stat"><b>{state.urges}</b><span>Urges paused</span></div><div className="stat"><b>{skipped}</b><span>Purchases skipped</span></div></div>{state.goals[0] && <div onClick={() => go('goals')}>{goalCard(state.goals[0])}</div>}<div className="link-grid"><button onClick={() => go('apps')}><Shield/>Protected apps</button><button onClick={() => go('wishlist')}><Clock3/>Wishlist</button><button onClick={() => go('goals')}><Leaf/>Savings goals</button><button onClick={() => go('history')}>♡ Insights</button></div>{native && !state.settings.protection && <button className="secondary" onClick={() => go('apps')}>Set up optional shopping app protection <ArrowRight size={16}/></button>}<p className="milestone">{protectedAmount >= 500 ? '🌳 Strong roots: $500 protected!' : protectedAmount >= 100 ? '🪴 Growing: $100 protected!' : state.urges ? '🌱 First pause planted!' : '🌱 Your first pause will plant the seed.'}</p></>}
 {page === 'new' && <>{back()}<h1>What caught<br/><em>your eye?</em></h1><p className="lead">Tell us about it. There are no wrong answers.</p><div className="card form"><label>Item name<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="What are you thinking of buying?"/></label><label>Price<input type="number" min="0" step="0.01" inputMode="decimal" value={draft.price} onChange={e => setDraft({ ...draft, price: e.target.value })} placeholder="0.00"/></label><label>Category<select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{['Other','Clothing','Home','Food & drink','Beauty','Tech','Hobbies','Pets','Gifts'].map(x => <option key={x}>{x}</option>)}</select></label><label>Product link (optional)<input type="url" value={draft.link} onChange={e => setDraft({ ...draft, link: e.target.value })} placeholder="https://..."/></label><label>Why do you want it?<textarea value={draft.why} onChange={e => setDraft({ ...draft, why: e.target.value })} placeholder="What would it do for you?"/></label><label>Current mood or trigger<input value={draft.trigger} onChange={e => setDraft({ ...draft, trigger: e.target.value })} placeholder="Bored, stressed, excited..."/></label><label>How would you describe it?<select value={draft.kind} onChange={e => setDraft({ ...draft, kind: e.target.value })}><option value="impulse">Impulse</option><option value="need">Need</option><option value="replacement">Replacement</option><option value="planned">Planned purchase</option></select></label><button className="primary" onClick={() => { if (!draft.name.trim() || draft.price === '' || Number(draft.price) < 0 || !Number.isFinite(Number(draft.price))) return setMessage('Add an item name and a valid price.'); go('pause'); }}>Take a pause <ArrowRight size={18}/></button></div></>}
 {page === 'pause' && <>{back('new')}<div className="breath"><span>pause · notice · choose</span></div><h1>A moment<br/><em>for you.</em></h1><p className="lead">Consider these gently. You can leave any answer blank.</p>{state.settings.questions.map((q, n) => <label className="question" key={n}><b>{String(n + 1).padStart(2,'0')} &nbsp; {q}</b><textarea value={answers[n] || ''} onChange={e => setAnswers({ ...answers, [n]: e.target.value })} placeholder="Your thoughts (optional)"/></label>)}<h2>Give it some time</h2><div className="choices">{WAIT_OPTIONS.map(([h,label]) => <button key={h} onClick={() => add(h)}>{label}{state.settings.cooldown === h ? ' · default' : ''} <ArrowRight size={16}/></button>)}</div><div className="row"><input type="number" min="1" step="1" inputMode="numeric" aria-label="Custom waiting time in minutes" placeholder="Custom minutes" value={custom} onChange={e => setCustom(e.target.value)}/><button onClick={() => Number.isInteger(Number(custom)) && Number(custom) > 0 ? add(Number(custom) / 60) : setMessage('Enter a waiting time in minutes.')}>Set wait</button></div><p className="hint">If you buy it, you can record that honestly later. Your pauses still count.</p></>}
 {page === 'wishlist' && <><h1>Your <em>waiting list.</em></h1><p className="lead">Time gives you more options, never fewer.</p><div className="eyebrow">COOLING DOWN · {waiting.length}</div>{!waiting.length && <div className="empty">Nothing waiting right now. Start with one small pause. 🌱</div>}{waiting.map(i => <div className="card item" key={i.id}><div className="row"><b>{i.name}</b><strong>{dollars(i.price)}</strong></div><div className="row muted"><span>{i.category} · {date(i.createdAt)}</span><span>{left(i.until)}</span></div><div className="progress"><i style={{ width: `${Math.min(100, Math.max(0, (now - i.createdAt) / (i.until - i.createdAt) * 100))}%` }}/></div><button className="text-button" onClick={() => setSelected(i)}>Review this item <ArrowRight size={16}/></button></div>)}<button className="primary" onClick={() => go('new')}><Plus size={18}/> Pause another purchase</button></>}
 {page === 'history' && <><h1>Your <em>progress.</em></h1><p className="lead">Every thoughtful choice belongs here, including purchases.</p><div className="stat-grid"><div className="stat"><b>{dollars(protectedAmount)}</b><span>Money protected</span></div><div className="stat"><b>{state.urges}</b><span>Urges paused</span></div><div className="stat"><b>{skipped}</b><span>Skipped</span></div><div className="stat"><b>{Math.max(state.best,currentStreak)} days</b><span>Personal best</span></div></div><div className="card"><b>{state.items.length ? Math.round(skipped / state.items.length * 100) : 0}% of recorded urges faded</b><p>Skipped items divided by all recorded items, including those still waiting.</p></div><h2>Milestones</h2><div className="badges">{[['🌱','First pause',state.urges >= 1],['🍃','Five pauses',state.urges >= 5],['🪴','$100 protected',protectedAmount >= 100],['🌳','$500 protected',protectedAmount >= 500],['☀️','Seven days',Math.max(state.best,currentStreak) >= 7]].map(([emoji,label,earned]) => <span className={earned ? '' : 'locked'} key={label}>{emoji} {label}</span>)}</div><h2>Patterns</h2><div className="card"><b>Categories</b><p>{Object.entries(state.items.reduce((a,i) => (a[i.category] = (a[i.category] || 0) + 1, a), {})).sort((a,b) => b[1] - a[1]).map(([k,v]) => `${k}: ${v}`).join(' · ') || 'No entries yet'}</p><b>Triggers</b><p>{Object.entries(state.items.reduce((a,i) => (a[i.trigger?.trim() || 'Not noted'] = (a[i.trigger?.trim() || 'Not noted'] || 0) + 1, a), {})).sort((a,b) => b[1] - a[1]).map(([k,v]) => `${k}: ${v}`).join(' · ') || 'No entries yet'}</p><b>When urges show up</b><p>{Object.entries(state.items.reduce((a,i) => { const key = new Date(i.createdAt).toLocaleDateString(undefined,{ weekday: 'long' }) + ' ' + (new Date(i.createdAt).getHours() < 12 ? 'morning' : new Date(i.createdAt).getHours() < 17 ? 'afternoon' : 'evening'); a[key] = (a[key] || 0) + 1; return a; }, {})).sort((a,b) => b[1] - a[1]).map(([k,v]) => `${k}: ${v}`).join(' · ') || 'No entries yet'}</p></div><h2>Item history</h2>{!state.items.length && <div className="empty">Your choices will appear here.</div>}{state.items.map(i => <div className="card item" key={i.id}><div className="row"><b>{i.name}</b><b>{dollars(i.price)}</b></div><div className="row muted"><span>{i.category} · {i.trigger || 'No trigger noted'}</span><span>{date(i.createdAt)}</span></div><small>{i.status === 'waiting' ? left(i.until) : i.status === 'skipped' ? 'Skipped · money protected' : i.status === 'cheaper' ? 'Found a cheaper alternative' : 'Purchased'}{i.extensions ? ` · extended ${i.extensions}×` : ''}</small>{i.link && <p><a href={i.link} target="_blank" rel="noopener noreferrer">Product link</a></p>}</div>)}</>}
 {page === 'goals' && <>{back()}<h1>What are you<br/><em>protecting?</em></h1><p className="lead">Assign skipped purchases to a goal. These are estimates, not transfers.</p>{state.goals.map(g => <div key={g.id}>{goalCard(g)}<button className="text-button" onClick={() => { if (confirm(`Delete ${g.name}?`)) set(d => ({ ...d, goals: d.goals.filter(x => x.id !== g.id) })); }}>Delete goal</button></div>)}<div className="card form"><h2>Add a goal</h2><label>Name<input value={goalDraft.name} onChange={e => setGoalDraft({ ...goalDraft, name: e.target.value })} placeholder="Emergency fund"/></label><label>Emoji<input value={goalDraft.icon} onChange={e => setGoalDraft({ ...goalDraft, icon: e.target.value })}/></label><label>Target amount<input type="number" min="1" value={goalDraft.target} onChange={e => setGoalDraft({ ...goalDraft, target: e.target.value })}/></label><label>Deadline (optional)<input type="date" value={goalDraft.deadline} onChange={e => setGoalDraft({ ...goalDraft, deadline: e.target.value })}/></label><button className="primary" onClick={() => { if (!goalDraft.name.trim() || !(Number(goalDraft.target) > 0)) return setMessage('Add a name and target above zero.'); set(d => ({ ...d, goals: [...d.goals, { ...goalDraft, id: uid(), target: Number(goalDraft.target), protected: 0 }] })); setGoalDraft({ name: '', icon: '🌱', target: '', deadline: '' }); }}>Save goal</button></div></>}
 {page === 'apps' && <>{back('settings')}<h1>Protected <em>apps.</em></h1><p className="lead">Choose where you want a gentle pause before shopping.</p><div className="card"><b>Optional Android accessibility access</b><p>When protection is on, Android tells Second Thought which app has opened. The service checks each opened app name against your selections and shows a pause screen only for selected apps. It does not save names of other apps. It does not read screen text, taps, purchases, or passwords. You can open an app temporarily or turn protection off at any time.</p>{native ? <><div className="row"><span>Accessibility service</span><b>{accessibility ? 'On' : 'Off'}</b></div>{state.settings.protectionConsent && <button className="secondary" onClick={() => Guard.openAccessibilitySettings()}>Open Android accessibility settings</button>}</> : <p>App protection is available on Android. Manual pauses work here too.</p>}</div><label className="switch-row">Enable protection<input type="checkbox" checked={state.settings.protection} onChange={e => e.target.checked ? startProtection() : set(d => ({ ...d, settings: { ...d.settings, protection: false, protectionConsent: false } }))}/></label><label>Temporary access (minutes)<input type="number" min="1" max="1440" value={state.settings.access} onChange={e => setting('access', Math.max(1, Math.min(1440, Number(e.target.value) || 10)))}/></label><h2>Installed launchable apps</h2>{!installed.length && <div className="empty">{native ? 'No apps found on this device.' : 'Select installed apps from the Android app.'}</div>}{installed.map(a => <label className="app-row" key={a.packageName}><span>{a.label}<small>{a.packageName}</small></span><input type="checkbox" checked={state.apps.includes(a.packageName)} onChange={e => set(d => ({ ...d, apps: e.target.checked ? [...d.apps, a.packageName] : d.apps.filter(p => p !== a.packageName) }))}/></label>)}</>}
 {page === 'settings' && <><h1>Your <em>settings.</em></h1><div className="settings-list"><button onClick={() => go('apps')}><Shield/> Protected apps <ArrowRight/></button><button onClick={() => go('goals')}><Leaf/> Savings goals <ArrowRight/></button></div><div className="card form"><h2>Your pauses</h2><label>Default cooldown<select value={state.settings.cooldown} onChange={e => setting('cooldown', Number(e.target.value))}>{WAIT_OPTIONS.map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></label><button className="secondary" onClick={() => go('questions')}>Edit reflection questions <ArrowRight size={16}/></button></div><div className="card"><h2>Notifications</h2><p>Optional reminders when a cooling period ends. Android asks for permission only after you enable this.</p><label className="switch-row">Cooldown reminders<input type="checkbox" checked={state.settings.notifications} onChange={async e => { if (e.target.checked && native && (await LocalNotifications.requestPermissions()).display !== 'granted') return setMessage('Notification permission was not granted.'); setting('notifications', e.target.checked); }}/></label></div><div className="card"><h2>Privacy & your data</h2><p>No account, bank connection, ads, analytics, subscription, or data sales. Entries stay on this device. Export makes a JSON copy you control. Uninstalling deletes local entries. Accessibility app detection is optional.</p><button className="secondary" onClick={() => go('privacy')}>Read privacy policy</button><button className="secondary" onClick={exportData}><Download size={16}/> Export local data</button><button className="danger" onClick={reset}><Trash2 size={16}/> Delete all data and reset app</button></div></>}
 {page === 'privacy' && <>{back('settings')}<h1>Your <em>privacy.</em></h1><p className="lead">How your purchase information stays on your device.</p><iframe className="policy-frame" src="/privacy-policy.html" title="Second Thought Spending privacy policy" /></>}
 {page === 'questions' && <>{back('settings')}<h1>Reflection <em>questions.</em></h1>{state.settings.questions.map((q,n) => <div className="row question-edit" key={n}><input value={q} onChange={e => setting('questions', state.settings.questions.map((v,i) => i === n ? e.target.value : v))}/><button aria-label="Remove question" onClick={() => setting('questions', state.settings.questions.filter((_,i) => i !== n))}><Trash2 size={17}/></button></div>)}<button className="secondary" onClick={() => setting('questions', [...state.settings.questions, ''])}><Plus size={17}/> Add a question</button><button className="text-button" onClick={() => setting('questions', defaults)}>Restore defaults</button></>}
 </main>{showDisclosure && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="disclosure-title"><div className="eyebrow">OPTIONAL APP PROTECTION</div><h2 id="disclosure-title">Before you turn it on</h2><p>To pause before selected shopping apps open, Second Thought: Spending uses Android Accessibility access to receive the package name of apps as they come to the foreground. This includes apps you did not select; those names are checked against your selections and are not saved.</p><p>If a selected app opens, we display a pause with your locally stored goal and estimated money protected. We do not read screen content, taps, messages, purchases, or passwords. We do not send app names or purchase information to a server or share them with anyone. You can turn protection off here or in Android Settings at any time. Manual purchase pauses work without this permission.</p><label className="switch-row"><span>I understand and agree to this optional access</span><input type="checkbox" checked={disclosureAccepted} onChange={e => setDisclosureAccepted(e.target.checked)}/></label><button className="primary" disabled={!disclosureAccepted} onClick={confirmProtection}>Agree and open Android settings</button><button className="secondary" onClick={() => setShowDisclosure(false)}>Not now</button></div></div>}<nav className="tabs">{[['home','Home'],['wishlist','Wishlist'],['history','History'],['settings','Settings']].map(([p,label]) => <button className={page === p ? 'active' : ''} key={p} onClick={() => go(p)}>{label}</button>)}</nav>{message && <div className="toast" role="status" onClick={() => setMessage('')}>{message} ×</div>}{selected && <div className="modal-backdrop"><div className="modal"><button className="close" onClick={() => setSelected(null)}>×</button><div className="eyebrow">A FRESH LOOK</div><h2>{selected.name}</h2><p>{dollars(selected.price)} · {left(selected.until)}</p>{selected.why && <p>Originally: “{selected.why}”</p>}<button className="primary" onClick={() => decide('skipped')}>Skip it · protect {dollars(selected.price)}</button>{state.goals.map(g => <button className="secondary" key={g.id} onClick={() => decide('skipped',g.id)}>Skip & assign to {g.icon} {g.name}</button>)}<button className="secondary" onClick={() => decide('purchased')}>Buy it · record without judgment</button><button className="secondary" onClick={() => decide('cheaper')}>Found a cheaper alternative</button><button className="text-button" onClick={() => extend(state.settings.cooldown)}>Wait longer ({state.settings.cooldown} hours)</button></div></div>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
